### ISSUE TITLE
How to monitor the multiple Queue using this ? 

### ISSUE THREAD

**Issue by harsh4870** [ryan-a-baker/k8s-scaling-demo#3]
i tried this solution. 

It's working very well but I have a scenario where I want to monitor the multiple queues in that case metrics files will be something like ?

if you can please share details on that ?

```
prometheus:
  url: http://prometheus-service.monitoring.svc.cluster.local
  port: 8080

rbac:
  create: true

serviceAccount:
  create: true

service:
  port: 443

logLevel: 6
rules:
  default: false
  custom:
  - seriesQuery: 'rabbitmq_queue_messages{kubernetes_name!="",kubernetes_namespace!=""}'
    resources:
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_name: {resource: "service"}
    metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,queue="create_event_agent_queue_fx"}) by (<<.GroupBy>>)
```

how to monitor multiple queues and based on that metrics implement the HPA for respective consumer deployment instead of single ?
